help:
	@bash ./argumentos.sh help
php:
	@bash ./argumentos.sh php	
python:
	@bash ./argumentos.sh python
mysql:
	@bash ./argumentos.sh mysql
base:
	@bash ./argumentos.sh base
sublime:
	@bash ./argumentos.sh sublime
phpmyadmin:
	@bash ./argumentos.sh phpmyadmin
deep:
	@bash ./argumentos.sh deep
docker:
	@bash ./argumentos.sh docker	
